import type { Content } from "./en";

export const de: Content = {
  meta: {
    title: "HomeServices — eine Plattform für jeden Haushaltsservice",
    description:
      "Eine komplette Plattform für Haushaltsdienstleistungen: Kunden-App, Partner-App für Unternehmen, Mitarbeiter und Selbstständige sowie ein Admin-Kontrollzentrum. Screens ansehen, Pitch-Decks laden und Kontakt aufnehmen.",
  },
  nav: {
    platform: "Plattform",
    showroom: "Showroom",
    apps: "Die Apps",
    business: "Geschäftsmodell",
    vision: "Vision",
    downloads: "Downloads",
    contact: "Kontakt",
    cta: "Kontakt aufnehmen",
    menu: "Menü",
    language: "Sprache",
    theme: "Hell-/Dunkelmodus umschalten",
  },
  hero: {
    eyebrow: "Plattform für Haushaltsservices · DACH",
    title: "Jeder Haushaltsservice.",
    titleAccent: "Eine vernetzte Plattform.",
    sub: "Eine Kunden-App, eine Partner-App für Unternehmen, Mitarbeiter und Selbstständige sowie ein Admin-Kontrollzentrum — gebaut, getestet und bereit für die erste Startregion.",
    ctaPrimary: "Showroom öffnen",
    ctaSecondary: "Decks herunterladen",
    pills: ["Kunden-App", "Partner-App", "Admin-Dashboard"],
    stats: [
      { v: "3", l: "vernetzte Produkte" },
      { v: "10", l: "Servicekategorien" },
      { v: "12 %", l: "transparente Plattformgebühr" },
      { v: "34", l: "automatisierte API-Tests" },
    ],
    scroll: "Entdecken",
  },
  platform: {
    eyebrow: "Die Plattform",
    title: "Drei Produkte. Ein Schwungrad.",
    sub: "Jede Buchung schafft Mehrwert für Kunden, für die Betriebe, die sie bedienen, und für den Betreiber, der die Qualität hochhält.",
    products: [
      {
        key: "client",
        name: "Kunden-App",
        tag: "Für Haushalte",
        text: "Geprüfte Profis finden, Preise vergleichen, Termin buchen, den Auftrag verfolgen — und im Notfall sofort Hilfe rufen.",
        points: ["10 Servicekategorien", "Notfall-SOS, rund um die Uhr", "Umzugsplaner", "Englisch · Deutsch · Französisch"],
      },
      {
        key: "business",
        name: "Partner-App",
        tag: "Für Betriebe",
        text: "Eine App für Betriebsleiter, ihre Mitarbeiter und Selbstständige: Disposition, Terminplan, Aufträge, Einnahmen und Profil.",
        points: ["Leiter · Mitarbeiter · Selbstständig", "Zuweisen und benachrichtigen mit einem Tipp", "Netto-Einnahmen, Gebühren sichtbar", "Englisch · Deutsch"],
      },
      {
        key: "admin",
        name: "Admin-Dashboard",
        tag: "Für den Betreiber",
        text: "Partner freigeben, jede Buchung und Zahlung im Blick behalten, Qualität und Datenschutz sichern — in einer Web-Konsole.",
        points: ["Freigeben · ablehnen · sperren", "Buchungen, Zahlungen, Bewertungen", "Bankdaten werden nie ausgespielt", "Englisch · Deutsch, responsiv"],
      },
    ],
    flywheel: {
      title: "Wie die Bausteine sich gegenseitig verstärken",
      steps: [
        { t: "Partner treten bei", d: "Unternehmen und Selbstständige bewerben sich und werden vom Admin freigegeben." },
        { t: "Kunden finden sie", d: "Freigegebene Partner erscheinen in der Kunden-App mit Bewertung und Preis." },
        { t: "Buchungen laufen", d: "Eine Buchung benachrichtigt den Leiter, der einen Mitarbeiter zuweist." },
        { t: "Qualität wächst", d: "Bewertungen und Kontrolle halten den Standard hoch und bringen Folgebuchungen." },
      ],
    },
  },
  showroom: {
    eyebrow: "Live-Showroom",
    title: "Jeder Screen aus der echten App.",
    sub: "Das sind Screenshots der laufenden Apps — keine Mock-ups. Produkt wechseln, nach Thema filtern und jeden Screen in voller Größe öffnen.",
    tabs: {
      client: "Kunden-App",
      manager: "Partner · Leiter",
      coworker: "Partner · Mitarbeiter",
      admin: "Admin-Dashboard",
    },
    tabNote: {
      client: "37 Screens · iOS & Android · dunkel und hell",
      manager: "14 Screens · die Sicht des Betriebsleiters",
      coworker: "4 Screens · Mitarbeiter sehen nur ihre eigene Arbeit",
      admin: "12 Screens · Web, vom Desktop bis zum Smartphone",
    },
    filters: {
      all: "Alle",
      discover: "Entdecken",
      booking: "Buchung",
      relocation: "Umzug",
      emergency: "Notfall",
      account: "Konto",
      dashboard: "Dashboard",
      jobs: "Aufträge",
      team: "Team",
      earnings: "Einnahmen",
      people: "Personen",
      money: "Zahlungen",
      quality: "Buchungen & Qualität",
    },
    appearance: { any: "Beliebig", light: "Hell", dark: "Dunkel" },
    counter: "von",
    prev: "Vorheriger Screen",
    next: "Nächster Screen",
    open: "In voller Größe öffnen",
    close: "Schließen",
    noMatch: "Keine Screens für diesen Filter.",
    thumbs: "Screens",
  },
  apps: {
    eyebrow: "Die Apps im Detail",
    title: "Gebaut für echte Aufträge.",
    sub: "Ein genauerer Blick darauf, was jedes Produkt leistet — und welches Problem es löst.",
    client: {
      name: "Kunden-App",
      tag: "Für Haushalte",
      lead: "Etwas zu Hause reparieren zu lassen, sollte kein Projekt sein. Die Kunden-App macht Suche, Terminplanung, Preise und Nachverfolgung zu wenigen Tipps.",
      features: [
        { icon: "search", t: "Entdecken und vergleichen", d: "Zehn Kategorien, Anbieterprofile mit Bewertung, Stundensatz, Entfernung und Leistungen. Unternehmen und Selbstständige nebeneinander." },
        { icon: "calendar", t: "In Minuten buchen", d: "Datum und Zeitfenster wählen, einmalig oder wiederkehrend, Adresse eintragen und vor der Bestätigung den vollen Preis sehen." },
        { icon: "receipt", t: "Transparente Preise", d: "Der Bruttopreis enthält 19 % MwSt., die Plattformgebühr steht in einer eigenen Zeile — keine Überraschung an der Haustür." },
        { icon: "siren", t: "Notfall-SOS", d: "Rohrbruch, Gasgeruch, Stromausfall, Wasserschaden oder ausgesperrt: Der nächste verfügbare Profi wird sofort benachrichtigt — mit Erste-Hilfe-Tipps für die Wartezeit." },
        { icon: "truck", t: "Umzugsplaner", d: "Entfernung von Stadt zu Stadt aus einer integrierten Liste, Empfehlung zwischen Umzugsunternehmen und selbstständigem Helfer sowie geschätzte Preise." },
        { icon: "message", t: "Chat und Benachrichtigungen", d: "Mit dem Anbieter in Kontakt bleiben und bei jeder Statusänderung Ihrer Buchung informiert werden." },
      ],
    },
    business: {
      name: "Partner-App",
      tag: "Für Unternehmen, Mitarbeiter und Selbstständige",
      lead: "Gute Handwerker müssen Disponent, Buchhalter und Marketer zugleich sein. Eine App gibt jeder Rolle genau das, was sie braucht — und nichts, was sie nicht sehen soll.",
      roles: [
        {
          icon: "building",
          name: "Betriebsleiter",
          sub: "Voller Zugriff",
          items: [
            "Dashboard: Einnahmen der Woche, offene Auszahlung, aktive Aufträge, Teamgröße",
            "Hinweis auf nicht zugewiesene Aufträge und Zuweisung mit einem Tipp samt Benachrichtigung des Mitarbeiters",
            "Verschieben, neu zuweisen oder stornieren; jeden Auftrag nach Status filtern",
            "Auslastung je Teammitglied; Mitarbeiter hinzufügen oder entfernen",
            "Umsatz nach Kategorie, Plattformgebühren und Team-Ranking",
          ],
        },
        {
          icon: "hardhat",
          name: "Mitarbeiter",
          sub: "Nur eigene Aufträge",
          items: [
            "Persönlicher Terminplan mit Monatskalender und Tagesaufträgen",
            "Kunde, Adresse, Zeit und Preis für jeden zugewiesenen Auftrag",
            "Statusmeldungen und Auftragsberichte",
            "Eigene Einnahmen mit Summen und Durchschnitt; Verfügbarkeitsschalter",
            "Kein Zugriff auf die Firmenfinanzen",
          ],
        },
        {
          icon: "wrench",
          name: "Selbstständig",
          sub: "Solo-Modus",
          items: [
            "Ein buchbares Profil neben etablierten Unternehmen",
            "Terminplan, Einnahmen und Profil in derselben App",
            "Steuer- und Auszahlungsdaten einmal erfasst, vertraulich behandelt",
            "Später auf derselben Plattform zum Unternehmen wachsen",
          ],
        },
      ],
    },
    admin: {
      name: "Admin-Dashboard",
      tag: "Für den Betreiber",
      lead: "Vertrauen ist das Produkt. Das Kontrollzentrum zeigt, wer auf der Plattform ist, was passiert und was sie verdient — ohne sensible Daten preiszugeben.",
      features: [
        { icon: "layout", t: "Übersicht", d: "Kunden, Unternehmen, Selbstständige und Mitarbeiter; Buchungen nach Status; Plattformeinnahmen; neueste Buchungen." },
        { icon: "badge", t: "Freigaben und Onboarding", d: "Bewerbungsliste mit Geschäftsdaten; mit einem Klick freigeben, ablehnen oder sperren." },
        { icon: "users", t: "Personenverzeichnis", d: "Unternehmen, Selbstständige, Mitarbeiter und Kunden — durchsuchbar, mit Status und Aktivität." },
        { icon: "calendar", t: "Buchungsüberblick", d: "Jede Buchung mit Adresse, Leistungen, Preisen und Zahlung — von der Anfrage bis zum Abschluss." },
        { icon: "euro", t: "Zahlungen und Umsatz", d: "Zahlungsdaten, Bruttovolumen im Verhältnis zur 12-%-Gebühr, Netto-Beträge je Anbieter." },
        { icon: "star", t: "Bewertungen und Qualität", d: "Alle Kundenbewertungen mit Wertung, Anbieter und Buchung — Probleme früh erkennen." },
      ],
    },
  },
  winners: {
    eyebrow: "Wem es hilft",
    title: "Wir lösen ein echtes Problem für alle in der Kette.",
    problem: "Das Problem",
    answer: "Unsere Antwort",
    items: [
      { icon: "home", who: "Kunden", problem: "Langsame Suche, intransparente Preise und stressige Notfälle.", answer: "Geprüfte Anbieter, feste Preise, 24/7-SOS, Chat und Bewertungen." },
      { icon: "building", who: "Unternehmen", problem: "Disposition per Telefon und Chat; kein Überblick über Aufträge, Team und Einnahmen.", answer: "Ein Dashboard für Aufträge, Zuweisung, Auslastung und Netto-Einnahmen." },
      { icon: "hardhat", who: "Mitarbeiter", problem: "Unklare Pläne, Berichte auf Papier, kein Blick auf den eigenen Verdienst.", answer: "Ein persönlicher Plan, nur die eigenen Aufträge und der eigene Verdienst." },
      { icon: "wrench", who: "Selbstständige", problem: "Tolles Handwerk, aber keine Zeit für Marketing, Buchung und Verwaltung.", answer: "Buchungen kommen zu ihnen; Terminplan und Einnahmen laufen in einer App." },
      { icon: "shield", who: "Plattform-Admin", problem: "Qualität und Vertrauen brechen ohne Steuerung und Überblick weg.", answer: "Freigaben, Kontosteuerung, Buchungs- und Umsatzkontrolle." },
    ],
  },
  business: {
    eyebrow: "Geschäftsmodell",
    title: "Wir verdienen, wenn Arbeit erledigt wird.",
    lead: "Ein fester Plattformanteil von 12 % an jeder abgeschlossenen Buchung. Keine Buchung, keine Gebühr — und die Apps zeigen Netto-Beträge, damit es bei der Auszahlung keine Überraschungen gibt.",
    split: { provider: "an den Anbieter", fee: "Plattformgebühr", caption: "Beispiel: eine Buchung über 100 €. Preise werden brutto inkl. 19 % MwSt. angezeigt; die Gebühr steht in einer eigenen Zeile." },
    points: [
      { icon: "check", t: "Erfolgsbasiert", d: "Partner zahlen nichts für den Beitritt und nichts, solange sie nichts verdienen." },
      { icon: "eye", t: "Transparent", d: "Die Gebühr ist für Kunden, Partner und Betreiber sichtbar." },
      { icon: "layers", t: "Spielraum für Wachstum", d: "Premium-Partnerwerkzeuge, B2B-Konten und Werbung sind später möglich und nicht Teil der folgenden Zahlen." },
    ],
    scale: {
      title: "Illustratives Skalierungsmodell",
      note: "Jahresgebühren = Partner × Aufträge pro Monat × 12 × Ø-Buchung × 12 %. Das sind Annahmen, die zeigen, wie das Modell skaliert — keine Prognose.",
      cols: ["Stufe", "Partner", "Aufträge / Monat je Partner", "Ø-Buchung", "Jahresgebühren"],
      rows: [
        ["Pilotstadt", "100", "20", "120 €", "345.600 €"],
        ["Region", "500", "25", "130 €", "2,34 Mio. €"],
        ["Mehrere Städte", "2.500", "30", "140 €", "15,12 Mio. €"],
      ],
    },
    market: {
      title: "Ein riesiger, fragmentierter Markt",
      lead: "Das deutsche Handwerk ist das Rückgrat lokaler Haushaltsservices — und überwiegend in kleinen, selbstständigen Betrieben organisiert, mit wenig digitaler Infrastruktur zwischen ihnen und ihren Kunden.",
      stats: [
        { v: "1,04 Mio.", l: "eingetragene Handwerksbetriebe" },
        { v: "5,6 Mio.", l: "Beschäftigte" },
        { v: "771 Mrd. €", l: "Jahresumsatz (ohne MwSt.)" },
        { v: "342 Tsd.", l: "Auszubildende" },
      ],
      insight: "Im Schnitt rund fünf Personen pro Betrieb — zu klein, um einen eigenen Buchungs-, Dispositions- und Zahlungsstack zu bauen.",
      source: "Quelle: ZDH (Zentralverband des Deutschen Handwerks), „Wirtschaftlicher Stellenwert des Handwerks 2024“, zdh.de. Umsatz ohne MwSt.",
    },
  },
  trust: {
    eyebrow: "Vertrauen und Technik",
    title: "Gebaut, damit sensible Daten dort bleiben, wo sie hingehören.",
    sub: "Qualität ist eingebaut: klare Rollen, minimale Datenweitergabe und automatisierte Tests.",
    items: [
      { icon: "badge", t: "Geprüfte Partner", d: "Jedes Unternehmen und jeder Selbstständige wird vom Admin geprüft und freigegeben (Entwurf → offen → freigegeben), bevor Buchungen möglich sind." },
      { icon: "lock", t: "Verschlüsselte Auszahlungsdaten", d: "IBAN, BIC und Bankname sind im Ruhezustand verschlüsselt (AES-256-GCM), erscheinen in den Apps als „Vertraulich“ und werden von der Admin-API nie ausgegeben." },
      { icon: "user", t: "Rollenbasierter Zugriff", d: "Kunden, Leiter, Mitarbeiter, Selbstständige und Admins erhalten nur die Daten und Aktionen ihrer Rolle — serverseitig durchgesetzt." },
      { icon: "server", t: "Tokens bleiben aus dem Browser", d: "Das Admin-Dashboard nutzt ein Backend-for-Frontend mit httpOnly-Cookies, sodass Seiten-Skripte Sitzungstokens nie lesen können." },
      { icon: "check", t: "Validiert und getestet", d: "Schema-validierte Eingaben und 34 automatisierte Integrationstests decken Authentifizierung, Buchungen, Benachrichtigungen und den Admin-Workflow ab." },
      { icon: "globe", t: "Gemacht für die DACH-Region", d: "Preise in Euro mit MwSt., deutsche Adressen und Städte zuerst sowie Apps in Englisch, Deutsch und Französisch." },
    ],
    stackTitle: "Technologie",
    stack: ["React Native · Expo", "Next.js · TypeScript", "Tailwind CSS", "Node.js · Express", "MySQL", "JWT · Zod", "Jest"],
  },
  vision: {
    eyebrow: "Die Zukunft",
    title: "Von der Buchungsplattform zum intelligenten Haushaltsservice-Netzwerk.",
    lead: "KI ist die nächste Schicht auf einem sauberen, strukturierten Buchungskern. Sie macht jeden Schritt schneller und genauer — und der Mensch behält die Kontrolle.",
    badge: "Roadmap — noch nicht gebaut",
    columns: [
      {
        icon: "home",
        who: "Für Kunden",
        items: [
          "Problem beschreiben oder Foto hochladen: Die KI schlägt Kategorie, Preisspanne und den passenden Profi vor",
          "Smartes Matching nach Verfügbarkeit, Entfernung, Bewertung und Preis",
          "Ein Dialog-Assistent zum Buchen und Verschieben auf Deutsch, Englisch oder Französisch",
          "Ein Umzugsschätzer aus Raumfotos oder Inventarlisten",
        ],
      },
      {
        icon: "building",
        who: "Für Partner",
        items: [
          "Smarte Disposition: der beste Mitarbeiter je Auftrag nach Fähigkeiten, Ort und Fahrzeit",
          "Ein Angebotsassistent, der aus Beschreibung und Fotos einen Angebotsentwurf erstellt",
          "Sprachberichte und automatisch vorbereitete Rechnungen",
          "Nachfrage- und Preisanalysen; Hinweise auf freie Kapazität",
        ],
      },
      {
        icon: "shield",
        who: "Für Betreiber",
        items: [
          "Onboarding-Prüfung: Dokumente lesen, USt-IDs validieren, Unstimmigkeiten markieren",
          "Betrugs- und Anomaliewarnungen bei Stornierungen, Preisen und Doppelkonten",
          "Bewertungsmoderation und Feedback-Zusammenfassungen je Partner",
          "„Frag deine Daten“ in normaler Sprache; Angebots- und Nachfrageprognosen",
        ],
      },
    ],
    principles: {
      title: "Grundsätze",
      items: [
        "Assistenten schlagen vor, Menschen entscheiden — nichts wird automatisch freigegeben, abgelehnt oder ausgezahlt.",
        "Datenschutz von Anfang an: Partnerdaten bleiben privat und DSGVO-konform.",
        "Aufgebaut auf den Signalen, die die Plattform bereits speichert: Abläufe, Zuweisungen, Kategorien, Bewertungen und Preise.",
      ],
    },
    roadmap: {
      title: "Roadmap",
      stages: [
        { tag: "Heute gebaut", items: ["Drei Apps auf einer sicheren API", "Buchungsablauf, Benachrichtigungen, Chat, Bewertungen", "Notfallbuchung und Umzugsplaner", "34 automatisierte Integrationstests"] },
        { tag: "Als Nächstes · 0–6 Monate", items: ["Live-Zahlungen über einen Zahlungsdienstleister", "Echte Push-Benachrichtigungen und Store-Veröffentlichung", "Live-Tracking und gespeicherte Adressen", "Produktivhosting, CI/CD und Monitoring"] },
        { tag: "Danach · 6–12 Monate", items: ["Rechnungen mit MwSt. und Auszahlungsbelege", "Angebote in der App und Kalendersynchronisierung", "Bewertungsmoderation und Streitfälle", "Mehr Städte und Kategorien"] },
        { tag: "Vision · 12–24 Monate", items: ["KI-Matching, Auftragsklärung und Disposition", "Premium-Partnerwerkzeuge und B2B-Konten", "Partner-API und Integrationen", "Expansion in DACH und die EU"] },
      ],
    },
  },
  downloads: {
    eyebrow: "Pitch-Dokumente",
    title: "Alles, was Sie für den nächsten Schritt brauchen.",
    sub: "Drei Executive Summaries (A4, 3 Seiten) und drei Pitch-Decks (16:9) — bereit zum Teilen mit Unternehmen, Investoren und Partnern.",
    deck: "Pitch-Deck",
    summary: "Executive Summary",
    pages: "Seiten",
    slides: "Folien",
    download: "PDF herunterladen",
    preview: "Im Browser öffnen",
    all: "Alles herunterladen (ZIP)",
    allNote: "Alle sechs Dokumente in einer Datei",
    groups: [
      { key: "Client", name: "Kunden-App", tag: "Für Haushalte" },
      { key: "Business", name: "Partner-App", tag: "Für Betriebe" },
      { key: "Admin", name: "Admin-Dashboard", tag: "Für den Betreiber" },
    ],
    brand: {
      title: "Brand-Kit",
      sub: "Das HomeServices-Logo — Hausdach, Wände und ein „Auftrag erledigt“-Haken.",
      files: [
        { file: "homeservices-logo-mark.svg", label: "Bildmarke · SVG" },
        { file: "homeservices-logo-mark.png", label: "Bildmarke · PNG" },
        { file: "homeservices-logo-horizontal-on-light.png", label: "Horizontal · heller Hintergrund" },
        { file: "homeservices-logo-horizontal-on-dark.png", label: "Horizontal · dunkler Hintergrund" },
      ],
    },
  },
  contact: {
    eyebrow: "Kontakt",
    title: "Bereit, es in Ihre Stadt zu bringen?",
    sub: "Wir suchen Pilotpartner, Investoren und strategische Partner. Erzählen Sie uns kurz von sich — wir antworten persönlich. Eine Live-Demo des funktionierenden Produkts gibt es auf Anfrage.",
    direct: "Oder direkt schreiben",
    person: "Yahya Dhaou · Gründer",
    interests: [
      { v: "pilot", l: "Pilotpartner (Unternehmen oder Selbstständig)" },
      { v: "investor", l: "Investor" },
      { v: "strategic", l: "Strategischer Partner" },
      { v: "demo", l: "Live-Demo anfragen" },
      { v: "other", l: "Etwas anderes" },
    ],
    form: {
      name: "Ihr Name",
      email: "E-Mail-Adresse",
      company: "Unternehmen (optional)",
      interest: "Mein Interesse als",
      message: "Nachricht",
      messagePh: "Worüber möchten Sie sprechen?",
      consent: "Ich bin einverstanden, dass meine Angaben zur Beantwortung dieser Anfrage verwendet werden. Es erfolgt keine Weitergabe an Dritte. Ich erhalte eine Bestätigungs-E-Mail.",
      send: "Nachricht senden",
      sending: "Wird gesendet …",
      ok: "Vielen Dank — Ihre Nachricht ist angekommen. Eine Bestätigung ist unterwegs in Ihr Postfach.",
      fail: "Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut oder schreiben Sie uns direkt.",
      unavailable: "Das Formular ist vorübergehend nicht verfügbar. Bitte schreiben Sie uns direkt per E-Mail.",
      limited: "Zu viele Nachrichten in kurzer Zeit. Bitte versuchen Sie es etwas später erneut.",
      invalid: "Bitte prüfen Sie die markierten Felder.",
      required: "Pflichtfeld",
      emailInvalid: "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
      tooShort: "Bitte schreiben Sie mindestens 10 Zeichen.",
    },
  },
  footer: {
    tagline: "Jeder Haushaltsservice. Eine vernetzte Plattform.",
    rights: "Alle Rechte vorbehalten.",
    note: "Screenshots stammen aus den laufenden Apps mit Demodaten.",
    top: "Nach oben",
  },
};
