export const en = {
  meta: {
    title: "HomeServices — one platform for every home service",
    description:
      "A complete home-services platform: a client app, a partner app for companies, coworkers and independents, and an admin control center. Explore the screens, download the pitch decks and get in touch.",
  },
  nav: {
    platform: "Platform",
    showroom: "Showroom",
    apps: "The apps",
    business: "Business",
    vision: "Vision",
    downloads: "Downloads",
    contact: "Contact",
    cta: "Get in touch",
    menu: "Menu",
    language: "Language",
    theme: "Toggle light / dark theme",
  },
  hero: {
    eyebrow: "Home services platform · DACH",
    title: "Every home service.",
    titleAccent: "One connected platform.",
    sub: "A client app, a partner app for companies, coworkers and independents, and an admin control center — built, tested and ready for a first launch region.",
    ctaPrimary: "Open the showroom",
    ctaSecondary: "Download the decks",
    pills: ["Client app", "Partner app", "Admin dashboard"],
    stats: [
      { v: "3", l: "connected products" },
      { v: "10", l: "service categories" },
      { v: "12%", l: "transparent platform fee" },
      { v: "34", l: "automated API tests" },
    ],
    scroll: "Explore",
  },
  platform: {
    eyebrow: "The platform",
    title: "Three products. One flywheel.",
    sub: "Every booking creates value for clients, for the businesses that serve them and for the operator that keeps quality high.",
    products: [
      {
        key: "client",
        name: "Client app",
        tag: "For households",
        text: "Discover verified professionals, compare prices, book a slot, follow the job — and call for help in an emergency.",
        points: ["10 service categories", "Emergency SOS, 24/7", "Relocation planner", "English · German · French"],
      },
      {
        key: "business",
        name: "Partner app",
        tag: "For businesses",
        text: "One app for company managers, their coworkers and independents: dispatch, schedule, jobs, earnings and profile.",
        points: ["Manager · Coworker · Independent", "Assign and notify in one tap", "Net earnings, fees visible", "English · German"],
      },
      {
        key: "admin",
        name: "Admin dashboard",
        tag: "For the operator",
        text: "Approve partners, oversee every booking and payment, and protect quality and privacy from one web console.",
        points: ["Approve · reject · suspend", "Bookings, payments, reviews", "Banking data never exposed", "English · German, responsive"],
      },
    ],
    flywheel: {
      title: "How the pieces reinforce each other",
      steps: [
        { t: "Partners join", d: "Companies and independents apply and are approved by the admin." },
        { t: "Clients find them", d: "Approved partners appear in the client app with ratings and prices." },
        { t: "Bookings flow", d: "A booking notifies the manager, who assigns a coworker." },
        { t: "Quality compounds", d: "Reviews and oversight keep standards high and bring repeat bookings." },
      ],
    },
  },
  showroom: {
    eyebrow: "Live showroom",
    title: "Every screen, from the real app.",
    sub: "These are screenshots taken from the running apps — not mock-ups. Switch products, filter by topic and open any screen full size.",
    tabs: {
      client: "Client app",
      manager: "Partner · Manager",
      coworker: "Partner · Coworker",
      admin: "Admin dashboard",
    },
    tabNote: {
      client: "37 screens · iOS & Android · dark and light",
      manager: "14 screens · the company manager's view",
      coworker: "4 screens · a coworker sees only their own work",
      admin: "12 screens · web, desktop to phone",
    },
    filters: {
      all: "All",
      discover: "Discover",
      booking: "Booking",
      relocation: "Relocation",
      emergency: "Emergency",
      account: "Account",
      dashboard: "Dashboard",
      jobs: "Jobs",
      team: "Team",
      earnings: "Earnings",
      people: "People",
      money: "Payments",
      quality: "Bookings & quality",
    },
    appearance: { any: "Any theme", light: "Light", dark: "Dark" },
    counter: "of",
    prev: "Previous screen",
    next: "Next screen",
    open: "Open full size",
    close: "Close",
    noMatch: "No screens match this filter.",
    thumbs: "Screens",
  },
  apps: {
    eyebrow: "The apps in detail",
    title: "Built around real jobs.",
    sub: "A closer look at what each product does — and the problem it removes.",
    client: {
      name: "Client app",
      tag: "For households",
      lead: "Getting something fixed at home shouldn't feel like a project. The client app turns discovery, scheduling, pricing and follow-up into a few taps.",
      features: [
        { icon: "search", t: "Discover and compare", d: "Ten categories, provider profiles with ratings, hourly rates, distance and services. Companies and independents side by side." },
        { icon: "calendar", t: "Book in minutes", d: "Pick a date and time slot, one-off or recurring, add the address and see the full price before confirming." },
        { icon: "receipt", t: "Transparent prices", d: "The gross price includes 19% VAT and the platform fee is shown as its own line — no surprises at the door." },
        { icon: "siren", t: "Emergency SOS", d: "Burst pipe, gas leak, no power, flooding or lock-out: the nearest available pro is notified instantly, with first-aid tips while you wait." },
        { icon: "truck", t: "Relocation planner", d: "City-to-city distance from a built-in list, a recommendation between a moving company and an independent helper, and estimated prices." },
        { icon: "message", t: "Chat and notifications", d: "Stay in touch with the provider and get notified about every status change of your booking." },
      ],
    },
    business: {
      name: "Partner app",
      tag: "For companies, coworkers and independents",
      lead: "Great craftspeople are forced to be dispatchers, accountants and marketers. One app gives each role exactly what it needs — and nothing it shouldn't see.",
      roles: [
        {
          icon: "building",
          name: "Company manager",
          sub: "Full access",
          items: [
            "Dashboard: earnings this week, pending payout, active jobs, team size",
            "Alert for unassigned jobs and one-tap assignment, with a notification to the coworker",
            "Reschedule, reassign or cancel; filter every job by status",
            "Team workload per member; add or remove coworkers",
            "Revenue by category, platform fees and team ranking",
          ],
        },
        {
          icon: "hardhat",
          name: "Coworker",
          sub: "Own jobs only",
          items: [
            "Personal schedule with a monthly calendar and today's jobs",
            "Client, address, time and price for each assigned job",
            "Status updates and job reports",
            "Own earnings with totals and averages; availability switch",
            "No access to company finances",
          ],
        },
        {
          icon: "wrench",
          name: "Independent",
          sub: "Solo mode",
          items: [
            "A bookable profile next to established companies",
            "Schedule, earnings and profile in the same app",
            "Tax and payout details captured once, kept confidential",
            "Grow into a company later on the same platform",
          ],
        },
      ],
    },
    admin: {
      name: "Admin dashboard",
      tag: "For the operator",
      lead: "Trust is the product. The control center shows who is on the platform, what is happening and what it earns — without exposing sensitive data.",
      features: [
        { icon: "layout", t: "Overview", d: "Clients, companies, independents and workers; bookings by state; platform earnings; recent bookings." },
        { icon: "badge", t: "Approvals and onboarding", d: "Application queue with business details; approve, reject or suspend with one click." },
        { icon: "users", t: "People directory", d: "Companies, independents, workers and clients — searchable, with status and activity." },
        { icon: "calendar", t: "Bookings oversight", d: "Every booking with address, services, pricing and payment, from request to completion." },
        { icon: "euro", t: "Payments and revenue", d: "Payment records, gross volume versus the 12% fee, provider net amounts." },
        { icon: "star", t: "Reviews and quality", d: "All client reviews with rating, provider and booking — spot problems early." },
      ],
    },
  },
  winners: {
    eyebrow: "Who it helps",
    title: "We solve a real problem for everyone in the chain.",
    problem: "The problem",
    answer: "Our answer",
    items: [
      { icon: "home", who: "Clients", problem: "Slow search, opaque prices and stressful emergencies.", answer: "Verified providers, upfront prices, 24/7 SOS, chat and reviews." },
      { icon: "building", who: "Companies", problem: "Dispatch by phone and chat; no overview of jobs, team and earnings.", answer: "One dashboard for jobs, assignment, workload and net earnings." },
      { icon: "hardhat", who: "Coworkers", problem: "Unclear schedules, paper reports, no view of what they earn.", answer: "A personal schedule, only their own jobs and their own earnings." },
      { icon: "wrench", who: "Independents", problem: "Great craft, but no time for marketing, booking and admin.", answer: "Bookings come to them; schedule and earnings run in one app." },
      { icon: "shield", who: "Platform admin", problem: "Quality and trust break without governance and visibility.", answer: "Approvals, account control, booking and revenue oversight." },
    ],
  },
  business: {
    eyebrow: "Business model",
    title: "We earn when work gets done.",
    lead: "A fixed 12% platform share of each completed booking. No booking, no fee — and the apps show net amounts so there are no surprises at payout.",
    split: { provider: "to the provider", fee: "platform fee", caption: "Example: a €100 booking. Prices are shown gross including 19% VAT; the fee appears as its own line item." },
    points: [
      { icon: "check", t: "Performance-based", d: "Partners pay nothing to join and nothing unless they earn." },
      { icon: "eye", t: "Transparent", d: "The fee is visible to clients, partners and the operator." },
      { icon: "layers", t: "Room to grow", d: "Premium partner tools, B2B accounts and advertising are possible later and are not part of the numbers below." },
    ],
    scale: {
      title: "Illustrative scale model",
      note: "Annual fees = partners × jobs per month × 12 × average booking × 12%. These are assumptions to show how the model scales — not a forecast.",
      cols: ["Stage", "Partners", "Jobs / month each", "Average booking", "Annual fees"],
      rows: [
        ["Pilot city", "100", "20", "€120", "€345,600"],
        ["Regional", "500", "25", "€130", "€2.34 M"],
        ["Multi-city", "2,500", "30", "€140", "€15.12 M"],
      ],
    },
    market: {
      title: "A giant, fragmented market",
      lead: "Germany's craft sector is the backbone of local home services — and most of it is organised in small independent businesses with little digital infrastructure between them and their customers.",
      stats: [
        { v: "1.04 M", l: "registered craft businesses" },
        { v: "5.6 M", l: "people employed" },
        { v: "€771 bn", l: "annual turnover (excl. VAT)" },
        { v: "342 k", l: "apprentices" },
      ],
      insight: "About five people per business on average — too small to build their own booking, dispatch and payment stack.",
      source: "Source: ZDH (Zentralverband des Deutschen Handwerks), “Wirtschaftlicher Stellenwert des Handwerks 2024”, zdh.de. Turnover excludes VAT.",
    },
  },
  trust: {
    eyebrow: "Trust and engineering",
    title: "Built so sensitive data stays where it belongs.",
    sub: "Quality is designed in: clear roles, minimal data exposure and automated tests.",
    items: [
      { icon: "badge", t: "Vetted partners", d: "Every company and independent is reviewed and approved by the admin (draft → pending → approved) before taking bookings." },
      { icon: "lock", t: "Encrypted payout data", d: "IBAN, BIC and bank name are encrypted at rest (AES-256-GCM), shown as “Confidential” in the apps and never returned by the admin API." },
      { icon: "user", t: "Role-based access", d: "Clients, managers, coworkers, independents and admins each get only the data and actions that match their role — enforced on the server." },
      { icon: "server", t: "Tokens stay off the browser", d: "The admin dashboard uses a backend-for-frontend with httpOnly cookies, so page scripts can never read session tokens." },
      { icon: "check", t: "Validated and tested", d: "Schema-validated input and 34 automated integration tests cover authentication, bookings, notifications and the admin workflow." },
      { icon: "globe", t: "Made for DACH", d: "Prices in euro with VAT, German-first addresses and cities, and apps in English, German and French." },
    ],
    stackTitle: "Technology",
    stack: ["React Native · Expo", "Next.js · TypeScript", "Tailwind CSS", "Node.js · Express", "MySQL", "JWT · Zod", "Jest"],
  },
  vision: {
    eyebrow: "The future",
    title: "From a booking platform to an intelligent home-services network.",
    lead: "AI is the next layer on top of a clean, structured booking core. It will make every step faster and more accurate — while people stay in control.",
    badge: "Roadmap — not yet built",
    columns: [
      {
        icon: "home",
        who: "For clients",
        items: [
          "Describe the problem or upload a photo: AI suggests the category, a price range and the best-fit pro",
          "Smart matching by availability, distance, ratings and price",
          "A conversational assistant to book and reschedule in German, English or French",
          "A relocation estimator from room photos or an inventory list",
        ],
      },
      {
        icon: "building",
        who: "For partners",
        items: [
          "Smart dispatch: the best coworker per job by skills, location and travel time",
          "A quote and scope assistant that turns a description and photos into a draft quote",
          "Voice job reports and auto-drafted invoices",
          "Demand and pricing insights; idle-capacity alerts",
        ],
      },
      {
        icon: "shield",
        who: "For operators",
        items: [
          "Onboarding checks: read documents, validate VAT IDs, flag inconsistencies",
          "Fraud and anomaly alerts on cancellations, prices and duplicate accounts",
          "Review moderation and per-partner feedback summaries",
          "“Ask your data” in plain language; supply and demand forecasts",
        ],
      },
    ],
    principles: {
      title: "Principles",
      items: [
        "Assistants propose, people decide — nothing is approved, rejected or paid out automatically.",
        "Privacy by design: partner data stays private and GDPR-conform.",
        "Built on the signals the platform already stores: lifecycles, assignments, categories, ratings and prices.",
      ],
    },
    roadmap: {
      title: "Roadmap",
      stages: [
        { tag: "Built today", items: ["Three apps on a secure API", "Booking lifecycle, notifications, chat, reviews", "Emergency booking and relocation planner", "34 automated integration tests"] },
        { tag: "Next · 0–6 months", items: ["Live payments through a payment provider", "Real push notifications and store release", "Live tracking and saved addresses", "Production hosting, CI/CD and monitoring"] },
        { tag: "Then · 6–12 months", items: ["Invoices with VAT and payout statements", "In-app quotes and calendar sync", "Review moderation and disputes", "More cities and categories"] },
        { tag: "Vision · 12–24 months", items: ["AI matching, scoping and dispatch", "Premium partner tools and B2B accounts", "Partner API and integrations", "Expansion across DACH and the EU"] },
      ],
    },
  },
  downloads: {
    eyebrow: "Pitch documents",
    title: "Everything you need to take the next step.",
    sub: "Three executive summaries (A4, 3 pages) and three pitch decks (16:9), ready to share with companies, investors and partners.",
    deck: "Pitch deck",
    summary: "Executive summary",
    pages: "pages",
    slides: "slides",
    download: "Download PDF",
    preview: "Open in browser",
    all: "Download everything (ZIP)",
    allNote: "All six documents in one file",
    groups: [
      { key: "Client", name: "Client app", tag: "For households" },
      { key: "Business", name: "Partner app", tag: "For businesses" },
      { key: "Admin", name: "Admin dashboard", tag: "For the operator" },
    ],
    brand: {
      title: "Brand kit",
      sub: "The HomeServices logo — house roof, walls and a “job done” check.",
      files: [
        { file: "homeservices-logo-mark.svg", label: "Logo mark · SVG" },
        { file: "homeservices-logo-mark.png", label: "Logo mark · PNG" },
        { file: "homeservices-logo-horizontal-on-light.png", label: "Horizontal · light background" },
        { file: "homeservices-logo-horizontal-on-dark.png", label: "Horizontal · dark background" },
      ],
    },
  },
  contact: {
    eyebrow: "Get in touch",
    title: "Ready to bring it to your city?",
    sub: "We are looking for pilot partners, investors and strategic partners. Tell us a little about you and we'll reply personally. A live, click-through demo of the working product is available on request.",
    direct: "Or write directly",
    person: "Yahya Dhaou · Founder",
    interests: [
      { v: "pilot", l: "Pilot partner (company or independent)" },
      { v: "investor", l: "Investor" },
      { v: "strategic", l: "Strategic partner" },
      { v: "demo", l: "Request a live demo" },
      { v: "other", l: "Something else" },
    ],
    form: {
      name: "Your name",
      email: "E-mail address",
      company: "Company (optional)",
      interest: "I am interested as",
      message: "Message",
      messagePh: "What would you like to discuss?",
      consent: "I agree that my details are used to reply to this request. Nothing is shared with third parties. I will receive a confirmation e-mail.",
      send: "Send message",
      sending: "Sending…",
      ok: "Thank you — your message has arrived. A confirmation is on its way to your inbox.",
      fail: "Something went wrong. Please try again, or write to us directly.",
      unavailable: "The form is temporarily unavailable. Please e-mail us directly.",
      limited: "Too many messages in a short time. Please try again a little later.",
      invalid: "Please check the highlighted fields.",
      required: "Required",
      emailInvalid: "Please enter a valid e-mail address.",
      tooShort: "Please write at least 10 characters.",
    },
  },
  footer: {
    tagline: "Every home service. One connected platform.",
    rights: "All rights reserved.",
    note: "Screenshots are taken from the running apps with demo data.",
    top: "Back to top",
  },
};

export type Content = typeof en;
